[game]
hostname = "Scavengers [The dev stage]"
desc = "Проект находится на стадии разработки. Чтобы получить больше информации обратиться в discord сообщество."
maxplayers = 130
soft_max_players = 120
map_rotation = true
role_timers = true
lobbyenabled = true
lobbyduration = 240
round_restart_time = 240
contraband_examine = false

[infolinks]
discord = "https://discord.gg/4d5Y7UspZQ"

[rules]
time = 1.0

[shuttle]
emergency = false
arrivals = false
auto_call_time = 0
grid_fill = false
preload_grids = false

[ic]
flavor_text = true
punctuation = false

[atmos]
space_wind = false

[ooc]
enable_during_round = false

[netres]
limit = 25.0

[npc]
max_updates = 300

[whitelist]
enabled = true
prototype_list = "basicWhitelist"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
preset_enabled = false
restart_enabled = true
map_enabled = false

[viewport]
maximum_width = 26

[admin]
see_own_notes = false

[hub]
advertise = false
